/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.spilikin.healthid.keycloak;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
