version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        JAVA_OPTS_APPEND: "-Dkeycloak.profile=preview -Dkeycloak.profile.feature.scripts=enabled"
      volumes:
        - ./dist/healthid-provider.jar:/opt/jboss/keycloak/standalone/deployments/healthid-provider.jar
        - ./healthid-authenticator/build/libs/healthid-authenticator.jar:/opt/jboss/keycloak/standalone/deployments/healthid-authenticator.jar
        - ./healthid-authenticator/theme/healthid-challenge.ftl:/opt/jboss/keycloak/themes/base/login/healthid-challenge.ftl
        - ./healthid-authenticator/theme/resources:/opt/jboss/keycloak/themes/base/login/resources/healthid

      ports:
          - 8080:8080
      depends_on:
        - postgres
